###########################################################
# Rename the file extension to ".yaml" (remove "_") to enable
###########################################################

name: Docker Series Builds

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}   
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}  
      run: |
        docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
    - name: docker build githubdocker
      run: |
        docker build ./c# -t maroofshaikh09/githubdocker:1.0.0
    - name: docker build nodejs
      run: |
        docker build ./nodejs -t maroofshaikh09/nodejs:1.0.0
    - name: docker build python
      run: |
        docker build ./python -t maroofshaikh09/python:1.0.0
    - name: docker push
      run: |
        docker push maroofshaikh09/githubdocker:1.0.0
        docker push maroofshaikh09/nodejs:1.0.0
        docker push maroofshaikh09/python:1.0.0
